name: Release to NPM

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make release to npm
        uses: epeli/npm-release@v1
        with:
          type: stable
          token: ${{ secrets.NPM_TOKEN_LYKHO }}
    
