name: Node CI

on: 
  pull_request:
    types: opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: action/setup-node@v1
      - run: npm install
      - run: npm run check
      - env:
          CI: true
